# Generated by Django 4.0.6 on 2022-07-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Ml Blogs', max_length=255),
        ),
    ]
