# Generated by Django 4.0.6 on 2022-07-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_application', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
